# Everything that's downloaded after cloning Chromium goes here.
# It will not work from main downloads.ini
[search_engines_data]
url = https://gist.githubusercontent.com/wukko/2a591364dda346e10219e4adabd568b1/raw/e75ae3c4a1ce940ef7627916a48bc40882d24d40/nonfree-search-engines-data.tar.gz
download_filename = nonfree-search-engines-data.tar.gz
sha256 = 00a87050fa3f941d04d67fb5763991e0b8ea399a88b505ab0e56dd263f06864c
output_path = ./third_party/search_engines_data/resources_internal

[onboarding]
version = 202605050730
url = https://github.com/imputnet/helium-onboarding/releases/download/%(version)s/helium-onboarding-%(version)s.tar.gz
download_filename = onboarding-page-%(version)s.tar.gz
sha256 = 18bcec95d753e76b71536dc5aa1c517663f38eb17d5bf6c3b36f7b76165c43ce
output_path = ./components/helium_onboarding

# If you are bumping this, you *NEED* to re-strip the assets.json
# file *every time* by using `devutils/clear-ublock-assets.js`.
[ublock_origin]
version = 1.70.0
url = https://github.com/imputnet/uBlock/releases/download/%(version)s/uBlock0_%(version)s.chromium.zip
sha256 = d36ad2515c8dac907d17ae56d015c91c97fe27980fca1dc7575d0dfdba68e0d4
download_filename = ublock-origin-%(version)s.zip
output_path = third_party/ublock
strip_leading_dirs = uBlock0.chromium
